_layouts/default.html, collections/guides/quickstart/get_started.md, collections/guides/tokenize_customer_data_in_browser/index.md, index.markdown
=> chore: Updating summary descriptions on home page

collections/concepts/what-are-atomic-tokens.md, collections/concepts/what-are-tokens.md, collections/guides/collect_payments/index.md, collections/guides/own_your_encryption_keys/index.md, collections/guides/quickstart/get_started.md, collections/guides/setup_first_reactor/setup_first_reactor.md, collections/guides/tokenize_customer_data_in_browser/index.md
=> chore: copy updates

_config.yml
=> chore: updating  og:image

collections/concepts/what-are-atomic-tokens.md, collections/concepts/what-are-tokens.md, collections/guides/collect_payments/index.md, collections/guides/own_your_encryption_keys/index.md, collections/guides/quickstart/get_started.md, collections/guides/setup_first_reactor/setup_first_reactor.md, collections/guides/style_elements/index.md, collections/guides/tokenize_customer_data_in_browser/index.md, index.markdown
- updating og:image everywhere
=> chore: updating og:image everywhere

.github/ISSUE_TEMPLATE.md, _layouts/default.html, collections/guides/own_your_encryption_keys/index.md, collections/guides/setup_first_reactor/setup_first_reactor.md, collections/guides/style_elements/index.md
=> ENG-1282 Update discord link

_includes/head.erb, _includes/header.html
=> chore: updating analytics

_includes/head.erb, _includes/header.html, _layouts/default.html
=> Cleaning up analytics

collections/guides/quickstart/get_started.md
- postman link was to the old page
=> chore: updating postman link to new collection

collections/guides/own_your_encryption_keys/index.md
- Update own your own encryption guide to show simplified key management
=> chore: update own your own encryption guide to show simplified key management

.github/dependabot.yml, package.json, yarn.lock
- Address dependabot bumps
- Add `dependabot.yml` file
=> ENG-601 - Dependabot bumps and add dependabot.yml

_layouts/default.html
- adding both the cookie notification and tag manage for analytics
=> adding iubenda and google tag manager for analytics

collections/guides/setup_first_reactor/setup_first_reactor.md
- Updates "Setup Your First Reactor" guide based on new permissions and changes to the react response.
=> ENG-1645 Updating "Setup Your First Reactor" guide

collections/guides/collect_payments/index.md
Updates code used in card guide and codesandbox link
=> ENG-1851 - fix: update card guide code

collections/guides/collect_payments/index.md, collections/guides/style_elements/index.md
Updates ~`elements.create`~ to `createElement` and ~`storeCreditCard`~ to `atomicCards.create`
=> ENG-1858 - feat: refer to new Elements consolidate interfaces

collections/concepts/what-are-atomic-tokens.md, collections/guides/setup_first_reactor/setup_first_reactor.md
=> feat: convert to use BT-API-KEY auth header

collections/guides/collect_payments/index.md
=> fix: update cards example link

_sass/custom/custom.scss, collections/guides/encrypt_us_bank_accounts/index.md, collections/guides/own_and_use_us_bank_accounts/index.md
- Creating a guide for collecting / using bank account information
- Creating a guide for updating an existing application that uses Bank Data
- Want to be able to add a Loom to this as well and a link to a "simple" loom as well.
=> adding bank account guide

collections/concepts/what-are-tokens.md
- Adds employer_id_number to list of token types
- Removes impact level column to reduce noise (instead of updating / adding another column for default vs min impact levels)
=> [ENG-2153] Add employer_id_number to guides

collections/guides/quickstarts/quickstart_curl.md
=> fixing curl code styles with bash vs shell

CNAME, README.md, _config.yml, _layouts/default.html, collections/concepts/what-are-applications.md, collections/concepts/what-are-tenants.md, collections/guides/quickstarts/quickstart_curl.md, collections/guides/quickstarts/quickstart_dotnet.md, collections/guides/quickstarts/quickstart_nodejs.md, collections/guides/quickstarts/quickstart_ruby.md
=> fix: update hostname to developer.basistheory.com

CNAME, README.md, _config.yml, _layouts/default.html, collections/concepts/what-are-applications.md, collections/concepts/what-are-tenants.md, collections/guides/quickstarts/quickstart_curl.md, collections/guides/quickstarts/quickstart_dotnet.md, collections/guides/quickstarts/quickstart_nodejs.md, collections/guides/quickstarts/quickstart_ruby.md
=> fix: rename developer to developers

_layouts/default.html, index.markdown
=> fix: fix header and update title of site

collections/guides/collect_cards_react/index.md, collections/guides/collect_charge_cards_js/index.md, collections/guides/collect_pii_js/index.md, collections/guides/collect_pii_react/index.md, collections/guides/encrypt_us_bank_accounts/index.md, collections/guides/own_and_use_us_bank_accounts/index.md, collections/guides/setup_first_reactor/setup_first_reactor.md, collections/guides/use_token_data_in_http_requests/index.md
Adds deep links to Customer Portal Create Application page on guides
=> ENG-2318 - Add create application deep link on guides

collections/guides/migrating_off_basis_theory/index.md
- Adding a new guide - content approved by Jordan, Nathan, Brandon.
=> adding miigration guide

collections/guides/encrypt_us_bank_accounts/index.md
=> fix: file name typo, app.json -> app.js

.github/ISSUE_TEMPLATE.md, collections/concepts/what-are-tokens.md, collections/guides/own_your_encryption_keys/index.md, collections/guides/quickstarts/quickstart_curl.md, collections/guides/quickstarts/quickstart_dotnet.md, collections/guides/quickstarts/quickstart_java.md, collections/guides/quickstarts/quickstart_nodejs.md, collections/guides/quickstarts/quickstart_python.md, collections/guides/quickstarts/quickstart_ruby.md, collections/guides/setup_first_reactor/setup_first_reactor.md, collections/guides/style_elements/index.md
=> chore: update community link

collections/concepts/what-are-tenants.md
- Add new FAQ to Tenants concept page outlining the ways to manage Tenant Members
=> feat: add tenant members FAQ to tenants concept

collections/concepts/what-are-fingerprints.md
- REL-31 - add fingerprint concept page
=> feat: add fingerprint concept page

collections/concepts/what-are-fingerprints.md, collections/concepts/what-are-reactors.md, collections/concepts/what-is-the-proxy.md
- Fixes the concept page ordering
=> fix: fix concepts ordering

collections/quickstarts/quickstart_dotnet.md, collections/quickstarts/quickstart_nodejs.md, collections/quickstarts/quickstart_python.md, collections/quickstarts/quickstart_ruby.md
- Updating each quickstart guide to have a link to our SDKs
=> feat: adding sdk links to each quickstart guide

_sass/custom/nav.scss, collections/guides/use/migrating-off-basis-theory.md, collections/guides/use/run-your-own-code-in-a-reactor.md
- Adds guide: 'Run Your Own Code in a Reactor'
(full screen screenshot messed up the header)
=> feat: Adding guide to 'Run Your Own Code in a Reactor'

collections/guides/manage/manage-reactor-formulas-terraform.md
=> fix: add space before link to request access to private beta

collections/guides/use/migrating-off-basis-theory.md
Removes unused SDK from Migrating Off Basis Theory Guide - Proxy option
=> fix: remove unused sdk in migrating off guide

collections/concepts/understanding-permissions.md, collections/concepts/what-are-applications.md, collections/concepts/what-are-mats.md, collections/concepts/what-are-tenants.md
- Adds new MAT concept page
- Adds some clarifying language to Tenants and Applications pages.
=> feat: Adds new MAT concept page

collections/labs/labs.md
- Fixing send secure lab code download link
=> fix: fixing send secure lab code download link

_sass/custom/custom.scss, collections/guides/secure/collect-pii-js.md
- Removing retrieveDecrypted example from guides
- Fix code styling
=> feat: Removing retrieveDecrypted example from guide

collections/concepts/what-are-fingerprints.md, collections/concepts/what-is-search.md
- clarify MAT usage with Search based on feedback
=> fix: clarify MAT usage with search

_sass/custom/home-page-cards.scss
- Fixes UI issue with home page cards on mobile devices.
phone:
tablet:
small desktop:
large desktop:
=> fix: fixes the way cards are displayed on mobile

collections/guides/use/collect-cards-with-elements.md
- Fixes links for codesandbox examples for collecting cards with elements
=> fix: fix links for codesandbox collect cards with elements example

_includes/nav.html, collections/concepts/what-are-mats.md, collections/concepts/what-is-the-proxy.md, collections/guides/use/run-your-own-code-in-a-reactor.md, collections/guides/use/use-token-data-in-reactors.md, collections/guides/use/use_token_data_in_http_requests.md, index.markdown
- Updating links to detokenization expression docs
=> feat: Updating links to docs for expressions and detokenization

collections/guides/use/run-your-own-code-in-a-reactor.md
- Removes private reactor notices now that they are out of beta
=> feat: remove private reactor notices

collections/guides/use/run-your-own-code-in-a-reactor.md, collections/guides/use/use_token_data_in_http_requests.md
=> feat: add additional info about proxy request options

collections/guides/use/collect-cards-with-proxies.md, collections/guides/use/migrating-off-basis-theory.md
- adds guide for collecting cards via Proxy
=> feat: adds guide for collecting cards via Proxy

_layouts/default.html, _sass/custom/header.scss, collections/guides/secure/style-elements-for-my-brand.md
Fixes Elements style font example
Fixes header links highlight
=> fix: elements font example

_sass/custom/custom.scss, _sass/custom/header.scss, _sass/custom/home-page.scss, _sass/custom/variables.scss, collections/labs/labs.md, collections/quickstarts/home.md, index.markdown
Updates heading font to Outfit
=> fix: use proper heading font

_sass/custom/custom.scss, collections/quickstarts/quickstart_go.md
=> fix: go syntax highlighting

_sass/custom/home-page-cards.scss, collections/quickstarts/home.md
- fix quickstart card size and alignment
=> fix: quickstart card size and alignment

.github/dependabot.yml, Gemfile.lock, package.json, yarn.lock
- Updates dependencies
- Configures dependabot for ruby gems
=> chore(deps): Update dependencies

collections/quickstarts/quickstart_ruby.md
- Removing out of date community gem from quickstart guide
=> fix: removing community library

collections/concepts/what-are-tokens.md
Fixes curly braces use in default fingerprint expressions
=> fix: default fingerprint expression

collections/guides/use/migrating-off-basis-theory.md
- Format JS code and wrap in liquid tags so they display as code blocks.
=> fix: format js code snippets

collections/concepts/access-controls.md, collections/concepts/what-are-containers.md, collections/concepts/what-are-mats.md
- Adding token containers concept page
=> adding containers concept page

collections/concepts/what-is-search.md
This is a PR to update the what-is-search page in order to accurately reflect the changes in searchable fields & search indexes. The new description is much leaner than what was there before, so please advise if anything can be added in so it's as explicit & clear as it can be for our users ✨
=> [ENG-3605] Update what-is-search to reflect product offering

collections/blueprints/pci.md
=> feat: pci blueprint code changes

collections/blueprints/pci.md
- fix bad link in PCI Blueprint that throws a 404
=> fix: bad link in pci blueprint

collections/concepts/what-are-mats.md
- Adding limits to the MAT concept page
=> Added limits to MAT concept

collections/guides/use/collect-cards-with-elements.md
=> defect: fixing broken links

collections/concepts/access-controls.md
- Update access controls concept page with expiring apps
=> feat: add expiring applications docs

collections/concepts/what-are-tokens.md, index.markdown
- Fixes link to access controls concept page on docs home page
- Updates text on concept page links
- Moves table of contents on Tokens concept page to match Access Controls
=> fix: Fixes link to access controls concept page

collections/concepts/what-are-reactors.md, collections/guides/manage/manage-reactor-formulas-terraform.md
Removes Reactor Formulas beta disclaimers
=> fix: remove reactor formulas beta disclaimer
